static/openapi.yaml

This PR depends on #14 
Previously the search response was inlined to the route. It is not done like this for any other route in this spec file. Therefore I moved it to `components/schemas`.
Additionally, this is better for people using this spec, as this also introduces a name for the object.

Move search results scheme to components in OpenAPI spec

---

static/openapi.yaml

Fixes a small typo which was causing the generated docs to be using a fallback name instead of the correct one.

Fix typo in x-displayName tag of team_member_model

---

static/openapi.yaml

In the OpenAPI spec, not in all cases properties are set to be required using `required: true`. When there is a list of properties in a schema, this has to be done using the `required` array of schema itself.

openapi: Fix wrong required attributes

---

static/openapi.yaml

Some parameters were wrongly specified as path parameters, while they actually were query parameters. Additionally, the don't have to be specified in the openapi path itself.
The schema of the requestBody for posting a new gallery image was missing - but it does have to be set to binary string. See https://swagger.io/docs/specification/describing-responses/ (response that returns a file).
The gallery array for a project version was missing the item type. I set it to string because it is an array of URLs.

openapi: Fix validity issues

---

static/openapi.yaml

In the schema definition, tags should be regular objects to allow projects consuming the OpenAPI scheme to generate sensible code.
The fact that tag routes return an array of tags should only be defined for their response, not in the tag schema itself.

openapi: Tag schemas should be regular objects

---

static/openapi.yaml

Currently, it's a bit confusing what should be used in order to generate the hash of a file, especially whether one should hash the file name, or the file's contents. This seems obvious once you know which one to use, but for someone from outside, this can generate quite a headache.
This PR aims to clarify a bit how to generate the hash, given a file, so that hopefully people will not have the same problems I once had :slightly_smiling_face:

openapi: Clarify what is hashed in a file

---

.github/workflows/documentation.yml
docusaurus.config.js
package.json
yarn.lock

This PR update all dependencies to higher versions.
For CI, I change to NodeJS 16.14 because it's a breaking change in [beta 2.0.0-21](https://docusaurus.io/changelog/2.0.0-beta.21) of docusaurus.

Update all dependencies to higher versions

---

docs/details/contributing.md

The sqlx-cli install will fail if `rustls` or `native-tls` is omitted, I chose `rustls` but either would work.

Add rustls to sqlx install features

---

static/openapi.yaml

Changes syntax to use YAML constructions.
This allows compatibility with the package [openapi-typescript](https://github.com/drwpow/openapi-typescript) which allows type checking in the frontend.
```diff
responses:
"200":
description: Search results
content:
application/json:
---           schema:
---             $ref: '#/components/schemas/SearchResults'
+++          schema: *SearchResults
```

Use YAML aliases and anchors

---

docs/details/ads.md

looks like someone forgot to replace this.
> Unfortunately, if Edge's tracking prevention mode is set to Strict, Edge will misidentify Carbon as a tracker for a dating site, which is false.
Is this also the case with Ethical? If not, this note could be removed, right?

Adblock msg: remove Edge and Firefox instructions

---

docs/details/ads.md

This is no longer relevant to Modrinth as of #72, and I forgot to mention that in said PR.

Remove Firefox tracking protection dropdown in ads page

---

static/welcome-channel.yaml

It seems that Modrinth emoji has been updated.
This PR changes it to the new emoji ID, perhaps this will fix the role menu not working? Who knows <img src="https://cdn.discordapp.com/emojis/815857962341761045.gif" alt="modCheck Emoji" width="22px" align="center">

Change custom emoji in role menu

---

docs/details/contributing.md

Added a small note about an issue I encountered while building. 
This avoids the following error when running `cargo build`
```
error: failed to run custom build command for `openssl-sys v0.9.80`
Caused by:
process didn't exit successfully: `/home/matt/Desktop/labrinth/target/debug/build/openssl-sys-656c216624ba9019/build-script-main` (exit status: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rustc-cfg=openssl
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset …
```

Add openssl requirement to contributing guidelines

---

static/openapi.yaml

This pr replaces `encoding`, `image`, `contentType` with `contentMediaType`. 
From what I read in the OpenAPI specification for version 3.1.0, this seems to be the correct property. See [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#considerations-for-file-uploads) for more info.
Also: I get an error when I run the openapi-generator to generate code with the current openapi file:
`attribute paths.'/project/{id|slug}/gallery'(post).requestBody.content.'image/*'.encoding.image is unexpected`
<details>
<summary>Steps to reproduce</summary>
- Download the latest openapi-generator from [here](https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.5.0-SNAPSHOT/) ([source on …

openapi: use contentMediaType to define type for image / icon upload

---

docs/details/contributing.md

This clarifies that some users may need to run `docker compose up` instead of `docker-compose up`, because Docker changed the command for docker-compose v2, which is shipping with recent versions of Docker
Reference: https://docs.docker.com/compose/compose-v2/

Add information about new docker compose

---

static/openapi.yaml

This pr adds the missing responses to the **patch** request on `/projects` that is used to edit multiple projects.
In [projects.rs#L1228 ](https://github.com/modrinth/labrinth/blob/master/src/routes/v2/projects.rs#L1228) I have seen that this can be returned:
- **204 (no content)** if successful
- **400 (invalid request)** if one of the requested projects was not found
- **401 (unauthorized)** if the user does not have permission to bulk edit this project or if the user is not a member of the project
- **404 (not found)** if the project status is hidden

openapi: Add responses to patchProjects

---

static/openapi.yaml

This PR replaces `*` and `&` with `$ref` for references.
**Why?**
**1. Specification**
I can not find an official description for `*` and `&`, however both seem to be working. Most editors and code-generators accept them. But `$ref` is mentioned in the official specification and also works.
https://swagger.io/docs/specification/using-ref/
https://spec.openapis.org/oas/v3.1.0#relativeReferencesURI
**2. Code generators**
Not all code-generators understand `*` and `&`. 
Example with the code generator for php:
`openapi-generator.jar generate -i static/openapi.yaml -g php -o ./apiclient`
When running without `--skip-validate-spec` I get the following errors:
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option …
```

openapi: use $ref for references

---

static/openapi.yaml

This pull request downgrades the Open API spec to 3.0.0 for broader support with generators and editors.
The `AlgorithmIdentifier` parameter is marked as not required, but all 3 endpoints that use it override this to make it required. Since this overriding seems to be unsupported in 3.0.0, I chose to set it to required in the component itself.
I added a `Image` component which lists the supported image types individually, as there seems to be no shorter syntax that actually works.
All image upload endpoints were updated to use this component.
There sadly doesn't seem to be a way to replace the `patternProperties` (used to upload images of versions directly in the `createProject` endpoint) in 3.0.0. I think removing these from the spec should be fine, as they are deprecated already.
The …

Downgrade Open API spec to 3.0.0 for broader support

---

docs/modpacks/playing_modpacks.md

I was a afraid I might have been too intrusive on the existing sentence there, so I'm open to any suggestions. BTW, I linked to the repo rather than [the specific docs page](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/), but let me know if that would be preferred.

Link to itzg/minecraft-server modpack support

---

static/openapi.yaml

It seems like someone forgot to add the ID property to the report schema

Add missing ID property to Report schema

---

static/support-channel.yaml

- <img src="https://cdn.discordapp.com/emojis/1140437823783190679.png?size=64" alt="Neoforge" height="18" align="center"> Added NeoForge link. It duplicates Forge one to prevent confusion among the users who may not yet aware of rebranding or forgot about it.
- <img src="https://cdn.discordapp.com/emojis/1140436034505674762.png?size=64" alt="Purpur" height="18" align="center"> Changed Purpur emoji ID. Previous emoji had unreadable colour in dark mode, so it was replaced with one that has better colour.

Update support channel links

---

docs/modpacks/format_definition.md

While this is not mentioned anywhere else yet, I assume this should be a valid dependency ID in the future.
We are certainly going to support this in our upcoming Prism Launcher 8.0 release!

mrpack format: add neoforge loader as valid dependency

---

docs/contributing.md

Added two notes for things that tripped me up during my initial setup for contribution.

Add notes to contributing docs to help initial setup

---

docs/faq/app/russia.md
docs/faq/app/russia.mdx
docs/faq/index.md

- Brought Russian translation to the top. Russian translation is done by
me so it may be pretty incorrect, but far better than machine
translation that used to be there already.
- Expanded on the reasons why Modrinth was banned to explain that it
wasn't the Modrinth that actually got banned, but Cloudflare IP
addresses.
- Explained how these bans work for the curious.
- Referenced tracking GitHub issue and invited to Discord community
where people can write us if they can help us with the ban.
- Change page language to Russian for better SEO. To be honest, English
section must be wrapped into a big div with lang="en" tag, but this
completely breaks markup. Too bad.

Expand on the ban in Russia app FAQ entry

---

static/openapi.yaml

The schema for the MultipleProjectIdentifier is currently defined as:
```yaml
schema:
type: array
items:
type: string
```
this is wrong.
It would mean that my request to fetch multiple projects would look like this:
`https://api.modrinth.com/v2/projects?ids=wKkoqHrH&ids=Ojp3IEa8`
```json
{
}
```
This PR changes the schema for MultipleProjectIdentifier to string.
New
```yaml
schema:
type: string
``` …

openapi: Change schema for MultipleProjectIdentifier to string

---

static/openapi.yaml

The schema `loaders` and `game_versions` in the endpoint `/project/{id|slug}/version` are currently defined as:
```yaml
- in: query
name: loaders
required: false
description: The types of loaders to filter for
schema:
type: array
items:
type: string
example: '["fabric"]'
- in: query
name: game_versions
required: false
description: The game versions to filter for
schema:
type: array
items:
type: string
example: '["1.18.1"]'
```
this is wrong.
It would mean that my request to list project versions would look like this:
`https://api.modrinth.com/v2/project/Ojp3IEa8/version?loaders=paper&loaders=spigot&game_versions=1.20.1&game_versions=1.20.2`
```json
{
"description": "Error while validating input: Query deserialize …
```

openapi: Change schema type for loaders and game_versions to string

---

static/openapi.yaml

The schema for the user IDs in `/users` is currently defined as:
```yaml
schema:
type: array
items:
type: string
```
this is wrong.
It would mean that my request to fetch multiple users would look like this:
`https://api.modrinth.com/v2/users?ids=vNcGR3Fd&ids=EBqEP7Kk`
```json
{
}
```
This PR changes the schema for the user ids to string.
New
```yaml
schema:
type: string
```
`https://api.modrinth.com/v2/users?ids=["vNcGR3Fd", "EBqEP7Kk"]`
Related to:
- …

openapi: Change schema for user ids to string

---

static/openapi.yaml

The schema for the notification IDs in `/notifications` is currently defined as:
```yaml
schema:
type: array
items:
type: string
```
this is wrong.
It would mean that my request to fetch notifications would look like this:
`https://api.modrinth.com/v2/notifications?ids=vNcGR3Fd&ids=EBqEP7Kk`
```json
{
}
```
This PR changes the schema for the notification IDs to string.
New
```yaml
schema:
type: string
``` …

openapi: Change schema for notification ids to string

---

static/openapi.yaml

The schema for the report IDs in `/reports` is currently defined as:
```yaml
schema:
type: array
items:
type: string
```
this is wrong.
It would mean that a request to fetch multiple reports would look like this:
`https://api.modrinth.com/v2/reports?ids=wKkoqHrH&ids=Ojp3IEa8`
```json
{
}
```
This PR changes the schema for the IDs to string.
New
```yaml
schema:
type: string
```
`https://api.modrinth.com/v2/reports?ids=["vNcGR3Fd", "EBqEP7Kk"]`
Related to:
- …

openapi: Change schema for report ids to string

---

static/openapi.yaml

The schema for the thread IDs in `/threads` is currently defined as:
```yaml
schema:
type: array
items:
type: string
```
this is wrong.
It would mean that my request to fetch multiple threads would look like this:
`https://api.modrinth.com/v2/threads?ids=vNcGR3Fd&ids=EBqEP7Kk`
```json
{
}
```
This PR changes the schema for the thread IDs to string.
New
```yaml
schema:
type: string
```
`https://api.modrinth.com/v2/threads?ids=["vNcGR3Fd", "EBqEP7Kk"]` …

openapi: Change schema for thread ids to string

---

static/openapi.yaml

The schema for the team IDs in `/teams` is currently defined as:
```yaml
schema:
type: array
items:
type: string
```
this is wrong.
It would mean that a request to fetch multiple teams would look like this:
`https://api.modrinth.com/v2/teams?ids=wKkoqHrH&ids=Ojp3IEa8`
```json
{
}
```
This PR changes the schema for the IDs to string.
New
```yaml
schema:
type: string
```
`https://api.modrinth.com/v2/teams?ids=["vNcGR3Fd", "EBqEP7Kk"]`
Related to:
- …

openapi: Change schema for team ids to string

---

static/openapi.yaml

The schema for the version IDs in `/versions` is currently defined as:
```yaml
schema:
type: array
items:
type: string
```
this is wrong.
It would mean that a request to fetch multiple versions would look like this:
`https://api.modrinth.com/v2/versions?ids=wKkoqHrH&ids=Ojp3IEa8`
```json
{
}
```
This PR changes the schema for the IDs to string.
New
```yaml
schema:
type: string
```
`https://api.modrinth.com/v2/versions?ids=["vNcGR3Fd", "EBqEP7Kk"]`
Related …

openapi: Change schema for version ids to string
