.github/workflows/documentation.yml
docs/tutorials/maven.md
sidebars.js

[Rendered view](https://github.com/wafflecoffee/docs/blob/5477f5598dc453146977d45409dd3ca8c266df6d/docs/tutorials/maven.md)
Please squash, I dunno what happened to the merging hell :P

Add comprehensive Modrinth Maven guide

---

docs/intro.md

Change somes mistakes on intro page

---

static/openapi.yaml

A added the fields which should always be present to the required block of the OpenAPI scheme.
I used the rust-src of labrinth for gathering this information.

Specifiy required fields in OpenAPI scheme

---

static/openapi.yaml

This PR depends on #14 
Previously in the scheme the `follows` property was specified as a common property between `Project` and `ProjectResult`, but that's not correct, as it is `follows` for `ProjectResult`, but `followers` for `Project`.

OpenAPI scheme fix followers property

---

static/openapi.yaml

This PR depends on #14 
This PR adds the following things:
- fixed the Team model (added `TeamMember`)
- documented the `project/{id|slug}/members` route
- added `TeamMember` to list of models

Fix and further document team API

---

static/openapi.yaml

Added the 3 query parameters `loaders`, `game_versions` and `featured`.

Document version route filter parameters

---

docusaurus.config.js

Detect the browsers theme preference to use as the default

Respect system color scheme

---

static/openapi.yaml

Merge when modrinth/labrinth#353 is merged

openapi: readd multiple version files routes

---

static/openapi.yaml

include array type and example for display_categories

openapi: display_categories items type and example

---

docs/modpacks/playing_modpacks.md

I added a reference to my project [mrpack-install](https://github.com/nothub/mrpack-install) for installing modpack servers.

mrpack-install reference

---

docusaurus.config.js

This PR re-config metada to use image field in theme configuration.
https://docusaurus.io/docs/next/api/themes/configuration#meta-image

Re-config image metadata.

---

static/roadmap-channel.yaml
static/welcome-channel.yaml

Also includes the roadmap channel but not sure if that's gonna end up being used.

Overhaul the Discord welcome channel

---

docs/details/contributing.md

Adds a small section about commands to run before opening a PR.
Adds a small section telling people they need to populate those two tables, before they can create a mod/modpack.

Update contributing steps for labrinth

---

package-lock.json
package.json

Update dependencies (Docusaurus & ReDocusaurus)

---

docs/details/contributing.md

Would help beginners (like me) to figure out what to do in terms of setting up the SQL database.

Add some information about setting up the SQL database on Modrinth

---

docs/details/contributing.md

Added some simple getting started documentation for the theseus launcher

Add getting started documentation for theseus

---

docs/modpacks/creating_modpacks.md

Hey :wave: !
I am the maintainer of [mc-modpack-kit](https://github.com/jh-devv/mc-modpack-kit) and I think it would be a great addition to add it in the docs for creating modpacks!

Add mention of mc-modpack-kit to creating_modpacks.md

---

static/openapi.yaml

This PR moves a few remaining response objects to schemas

Move more response objects to schemas

---

docs/contributing.md

Add documentation for running the API itself, which could puzzle some [users](https://discord.com/channels/734077874708938864/1103139849852162158/1158106083022360687).

Add labrinth cargo run documentation

---

static/openapi.yaml

Add missing items and type properties on NotificationAction

Fix NotificationAction in openapi.yaml

---

README.md
docs/contributing.md
docs/faq/index.md
docusaurus.config.js
package.json
pnpm-lock.yaml

All is in the title.
I think we can update the documentation with the release candidate (no futur breaking changes normally).
https://github.com/facebook/docusaurus/discussions/9429
https://twitter.com/sebastienlorber/status/1715309311767831033

Update to Docusaurus v3
